$("#ogFYI").change(function() {
    var text = $(this).val();
    text = text.replaceAll(/FYI.../g, "");
    text = text.replaceAll(/FYI../g, "");
    text = text.replaceAll(/FYI./g, "");
    text = text.replaceAll(/FYI-/g, "");
    text = text.replaceAll(/FYI - /g, "");
    text = text.replaceAll(/F.Y.I./g, "");
    text = text.replaceAll(/F.Y.I/g, "");
    text = text.replaceAll(/fyi.../g, "");
    text = text.replaceAll(/fyi../g, "");
    text = text.replaceAll(/fyi./g, "");
    text = text.replaceAll(/fyi -/g, "");
    text = text.replaceAll(/fyi-/g, "");
    text = text.replaceAll(/f.y.i./g, "");
    text = text.replaceAll(/f.y.i/g, "");
    text = text.replaceAll(/fyi/g, "");
    text = text.replaceAll(/Fyi/g, "");
    text = text.replaceAll(/Fyi /g, "");
    text = text.replaceAll(/FYi/g, "");
    text = text.replaceAll(/fYi/g, "");
    text = text.replaceAll(/fyI/g, "");
    text = text.replaceAll(/FYI/g, "");
    $("#correctMessage").text("fyi - " + text);
});
