$("#ogFYI").change(function() {
    var text = $(this).val();
    text = text.replaceAll("FYI...", "");
    text = text.replaceAll("FYI..", "");
    text = text.replaceAll("FYI.", "");
    text = text.replaceAll("FYI-", "");
    text = text.replaceAll("FYI - ", "");
    text = text.replaceAll("F.Y.I.", "");
    text = text.replaceAll("F.Y.I", "");
    text = text.replaceAll("fyi...", "");
    text = text.replaceAll("fyi..", "");
    text = text.replaceAll("fyi.", "");
    text = text.replaceAll("fyi -", "");
    text = text.replaceAll("fyi-", "");
    text = text.replaceAll("f.y.i.", "");
    text = text.replaceAll("f.y.i", "");
    text = text.replaceAll("fyi", "");
    text = text.replaceAll("Fyi", "");
    text = text.replaceAll("Fyi ", "");
    text = text.replaceAll("FYi", "");
    text = text.replaceAll("fYi", "");
    text = text.replaceAll("fyI", "");
    text = text.replaceAll("FYI", "");
    $("#correctMessage").text("fyi - " + text);
});
